#!/usr/bin/env bash
# Generate .env and certs/ca.pem from an existing Aiven for Apache Kafka service.
#
# Usage: ./scripts/aiven-env.sh <aiven-project> <kafka-service>
# Requires: avn (pip install aiven-client) with avn user login, plus jq.
#
# This script only reads: nothing is changed on the Aiven side.
set -euo pipefail

PROJECT="${1:-}"
SERVICE="${2:-}"

if [[ -z "$PROJECT" || -z "$SERVICE" ]]; then
    echo "Usage: $0 <aiven-project> <kafka-service>" >&2
    exit 1
fi

for bin in avn jq; do
    command -v "$bin" >/dev/null || { echo "$bin is required." >&2; exit 1; }
done

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
mkdir -p certs

echo "Reading service $SERVICE (project $PROJECT)…"
INFO="$(avn service get "$SERVICE" --project "$PROJECT" --json)"

# Components: find Kafka's SASL listener and the schema_registry URI.
SASL_HOST="$(jq -r '
  [.components[]? | select(.component=="kafka" and .kafka_authentication_method=="sasl" and .route=="dynamic")][0]
  | if . then "\(.host):\(.port)" else empty end' <<<"$INFO")"

if [[ -z "$SASL_HOST" ]]; then
    echo "No SASL listener found: enable kafka_authentication_methods.sasl on the service." >&2
    echo "  avn service update $SERVICE --project $PROJECT -c kafka_authentication_methods.sasl=true" >&2
    exit 1
fi

SR_URI="$(jq -r '
  [.components[]? | select(.component=="schema_registry" and .route=="dynamic")][0]
  | if . then "https://\(.host):\(.port)" else "" end' <<<"$INFO")"

USERNAME="$(jq -r '.users[0].username // "avnadmin"' <<<"$INFO")"
PASSWORD="$(jq -r '.users[0].password // ""' <<<"$INFO")"

# Project CA, required for the Java truststore.
avn project ca-get --project "$PROJECT" > certs/ca.pem
echo "CA written to certs/ca.pem"

cat > .env <<EOF
# Generated by scripts/aiven-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Project $PROJECT / service $SERVICE — DO NOT COMMIT
KAFKA_CLUSTER_NAME=$SERVICE
KAFKA_BOOTSTRAP_SERVERS=$SASL_HOST
KAFKA_SASL_MECHANISM=SCRAM-SHA-512
KAFKA_SASL_USERNAME=$USERNAME
KAFKA_SASL_PASSWORD=$PASSWORD
SCHEMA_REGISTRY_URL=$SR_URI
SCHEMA_REGISTRY_USER=$USERNAME
SCHEMA_REGISTRY_PASSWORD=$PASSWORD
KAFKA_CLUSTERS_0_READONLY=true
EOF

echo ".env written. Next: docker compose -f compose.dev.yaml up --build"
if [[ -z "$SR_URI" ]]; then
    echo "Note: Karapace Schema Registry is not enabled on this service — SCHEMA_REGISTRY_URL is empty."
fi
