#!/usr/bin/env bash
# Generate .env entries and certs/ca-N.pem from an existing Aiven for Apache
# Kafka service.
#
# Usage: ./scripts/aiven-env.sh <aiven-project> <kafka-service> [cluster-index]
#
#   cluster-index defaults to 0 and rewrites .env from scratch.
#   Any other index appends that cluster's block to an existing .env, so several
#   Aiven services can be collected into one UI:
#
#     ./scripts/aiven-env.sh prod-project kafka-prod 0
#     ./scripts/aiven-env.sh staging-project kafka-staging 1
#
# Requires: avn (pip install aiven-client) with avn user login, plus jq.
# This script only reads: nothing is changed on the Aiven side.
set -euo pipefail

PROJECT="${1:-}"
SERVICE="${2:-}"
INDEX="${3:-0}"

if [[ -z "$PROJECT" || -z "$SERVICE" ]]; then
    echo "Usage: $0 <aiven-project> <kafka-service> [cluster-index]" >&2
    exit 1
fi

if ! [[ "$INDEX" =~ ^[0-9]+$ ]]; then
    echo "cluster-index must be a number, got: $INDEX" >&2
    exit 1
fi

for bin in avn jq; do
    command -v "$bin" >/dev/null || { echo "$bin is required." >&2; exit 1; }
done

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
mkdir -p certs

echo "Reading service $SERVICE (project $PROJECT) as cluster $INDEX…"
INFO="$(avn service get "$SERVICE" --project "$PROJECT" --json)"

# Components: find Kafka's SASL listener and the schema_registry URI.
SASL_HOST="$(jq -r '
  [.components[]? | select(.component=="kafka" and .kafka_authentication_method=="sasl" and .route=="dynamic")][0]
  | if . then "\(.host):\(.port)" else empty end' <<<"$INFO")"

if [[ -z "$SASL_HOST" ]]; then
    echo "No SASL listener found: enable kafka_authentication_methods.sasl on the service." >&2
    echo "  avn service update $SERVICE --project $PROJECT -c kafka_authentication_methods.sasl=true" >&2
    exit 1
fi

SR_URI="$(jq -r '
  [.components[]? | select(.component=="schema_registry" and .route=="dynamic")][0]
  | if . then "https://\(.host):\(.port)" else "" end' <<<"$INFO")"

USERNAME="$(jq -r '.users[0].username // "avnadmin"' <<<"$INFO")"
PASSWORD="$(jq -r '.users[0].password // ""' <<<"$INFO")"

# Project CA, required for the Java truststore. One file per cluster, because
# two Aiven projects have two different CAs.
CA_FILE="certs/ca-${INDEX}.pem"
avn project ca-get --project "$PROJECT" > "$CA_FILE"
echo "CA written to $CA_FILE"

# Index 0 starts a fresh file; higher indices append to it.
if [[ "$INDEX" == "0" ]]; then
    cat > .env <<EOF
# Generated by scripts/aiven-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT COMMIT — this file holds live credentials.
EOF
elif [[ ! -f .env ]]; then
    echo "No .env found: run this script with index 0 first." >&2
    exit 1
fi

if grep -q "^KAFKA_${INDEX}_BOOTSTRAP_SERVERS=" .env 2>/dev/null; then
    echo "Cluster $INDEX is already present in .env — remove its block first." >&2
    exit 1
fi

cat >> .env <<EOF

# --- cluster $INDEX: project $PROJECT / service $SERVICE ---
KAFKA_${INDEX}_NAME=$SERVICE
KAFKA_${INDEX}_BOOTSTRAP_SERVERS=$SASL_HOST
KAFKA_${INDEX}_SASL_MECHANISM=SCRAM-SHA-512
KAFKA_${INDEX}_SASL_USERNAME=$USERNAME
KAFKA_${INDEX}_SASL_PASSWORD=$PASSWORD
KAFKA_${INDEX}_CA_CERT_FILE=/certs/ca-${INDEX}.pem
KAFKA_${INDEX}_SCHEMA_REGISTRY_URL=$SR_URI
KAFKA_${INDEX}_SCHEMA_REGISTRY_USER=$USERNAME
KAFKA_${INDEX}_SCHEMA_REGISTRY_PASSWORD=$PASSWORD
KAFKA_${INDEX}_READONLY=true
EOF

echo "Cluster $INDEX appended to .env"
if [[ -z "$SR_URI" ]]; then
    echo "Note: Karapace is not enabled on this service — the registry URL is empty."
fi
echo "Next: docker compose -f compose.dev.yaml up --build"
